name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya cambios en la rama main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Listar archivos original
        run: ls -l
      - name: Entrar a carpeta proyecto
        run: |
          cd newyork-hub
          ls -l
          npm install
          npm install three
          npm install three@latest
          npm install --save-dev typescript @types/three
          npm install d3
          npm i --save-dev @types/d3
          npm install @tweenjs/tween.js
          npm run build

      - name: Desplegar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: newyork-hub/dist
